In [63]:
#importando as biblioteca da api
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder

In [64]:
#buscando todos os jogos
result = leaguegamefinder.LeagueGameFinder()
todosJogos = result.get_data_frames()[0]

In [65]:
#importando as biblioteca usadas para previsao
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [66]:
#convertendo os dados para um dataFrame
df = pd.DataFrame(todosJogos)
#tranforma um dataframe em um csv
#df.to_csv("teste.csv")

In [67]:
#listando o dataFrame
df.head()
#df.columns

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,12019,1610612763,MEM,Memphis Grizzlies,0011900020,2019-10-08,MEM vs. NZB,W,241,108,...,0.800,11,45,56,22,3,11,21,17,14.0
1,12019,15018,GUA,Guangzhou Long-Lions,0011900018,2019-10-08,GUA @ PHI,L,240,86,...,0.810,6,34,40,12,3,1,23,29,-58.0
2,12019,1610612755,PHI,Philadelphia 76ers,0011900018,2019-10-08,PHI vs. GUA,W,241,144,...,0.703,15,36,51,35,10,5,8,22,58.0
3,12019,1610612756,PHX,Phoenix Suns,0011900022,2019-10-08,PHX vs. MIN,W,239,111,...,0.762,11,38,49,20,9,4,29,22,5.0
4,12019,1610612757,POR,Portland Trail Blazers,0011900023,2019-10-08,POR vs. DEN,L,240,94,...,0.765,15,36,51,19,11,4,22,24,-11.0

In [68]:
# Selecionando o que me interessa da base
df.drop(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP'], axis=1, inplace=True)
df.head()

,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,W,241,108,41,89,0.461,10,27,0.370,16,...,0.800,11,45,56,22,3,11,21,17,14.0
1,L,240,86,30,78,0.385,9,32,0.281,17,...,0.810,6,34,40,12,3,1,23,29,-58.0
2,W,241,144,51,96,0.531,16,43,0.372,26,...,0.703,15,36,51,35,10,5,8,22,58.0
3,W,239,111,44,88,0.500,7,23,0.304,16,...,0.762,11,38,49,20,9,4,29,22,5.0
4,L,240,94,31,91,0.341,6,30,0.200,26,...,0.765,15,36,51,19,11,4,22,24,-11.0

In [81]:
'''for x in range(df['WL'].size-1):
    if df['WL'][x] == 'L':
        df['WL'][x] = 'l'
    else:
        df['WL'][x] = 'w'''

"for x in range(df['WL'].size-1):\n    if df['WL'][x] == 'L':\n        df['WL'][x] = 'l'\n    else:\n        df['WL'][x] = 'w"

In [78]:
#Transformando os dados categÃ³ricos de FTR para numeros
from sklearn.preprocessing import LabelEncoder
# Create a label (category) encoder object
le = LabelEncoder()
# Fit the encoder to the pandas column
le.fit(df['WL'])
# Apply the fitted encoder to the pandas column
df['WL'] = le.transform(df['WL'])

In [79]:
df

,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,2,241,108,41,89,0.461,10,27,0.370,16,...,0.800,11,45,56,22,3,11,21,17,14.0
1,1,240,86,30,78,0.385,9,32,0.281,17,...,0.810,6,34,40,12,3,1,23,29,-58.0
2,2,241,144,51,96,0.531,16,43,0.372,26,...,0.703,15,36,51,35,10,5,8,22,58.0
3,2,239,111,44,88,0.500,7,23,0.304,16,...,0.762,11,38,49,20,9,4,29,22,5.0
4,1,240,94,31,91,0.341,6,30,0.200,26,...,0.765,15,36,51,19,11,4,22,24,-11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1,240,102,41,81,0.506,8,19,0.421,12,...,0.571,12,26,38,26,8,4,9,23,-2.0
29996,2,240,111,38,77,0.494,9,19,0.474,26,...,0.867,12,25,37,14,8,4,13,27,9.0
29997,2,241,97,42,86,0.488,7,18,0.389,6,...,0.600,12,31,43,26,5,6,9,13,10.0
29998,1,240,90,28,82,0.341,6,19,0.316,28,...,0.875,9,34,43,15,7,6,9,17,-1.0
29999,0,241,115,44,91,0.484,13,25,0.520,14,...,0.700,14,27,41,25,8,6,19,20,4.0

In [80]:
scaler = StandardScaler()
scaler.fit(df.drop('WL',axis=1))
from sklearn.preprocessing import StandardScaler scaler.transform(df.drop('WL',axis=1))
df_param = pd.DataFrame(df_normalizado, columns=df.columns[1:])
df_param.head()

SyntaxError: invalid syntax (<ipython-input-80-27f0a428ca86>, line 3)