In [33]:
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
nba_teams = teams.get_teams()
season = []
for team in nba_teams:
    print(nba_teams[0]['id'])

1610612737

In [36]:
'''for team in nba_teams:
    gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=team['id'])
    games = gamefinder.get_data_frames()[0]
    #season.append(games[0])
    #season.head()'''
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=nba_teams[0]['id'])
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22019,1610612737,ATL,Atlanta Hawks,1521900072,2019-07-12,ATL @ SAS,W,201,80,...,0.850,13,23,36,14,15.0,3,12,24,8.0
1,22019,1610612737,ATL,Atlanta Hawks,1521900060,2019-07-11,ATL @ WAS,L,200,71,...,0.700,9,28,37,19,10.0,8,22,25,-5.0
2,22019,1610612737,ATL,Atlanta Hawks,1521900042,2019-07-09,ATL vs. IND,W,202,87,...,0.708,7,27,34,17,5.0,5,18,21,18.2
3,22019,1610612737,ATL,Atlanta Hawks,1521900023,2019-07-07,ATL vs. MIN,L,178,60,...,0.625,9,27,36,7,7.0,10,18,28,-24.0
4,22019,1610612737,ATL,Atlanta Hawks,1521900023,2019-07-07,ATL vs. MIN,None,21,6,...,0.500,1,2,3,1,0.0,1,4,2,0.0

NameError: name 'game' is not defined